#!/usr/bin/env bash
set -e

if [[ $# -lt 1 ]]; then
  echo "Usage: ./run install | ./run test | ./run /absolute/path/to/url_file"
  exit 1
fi

case "$1" in
  install)
    echo "[stub] Installing dependencies..."
    pip install --user -r requirements.txt
    exit 0
    ;;
  test)
    echo "[stub] Running test suite..."
    # later: pytest with coverage
    pytest --cov=src tests/*
    exit 0
    ;;
  *) # absolute path assumed = URL_FILE
    echo "Running CLIApp(file)..."
    python -m src.CLIApp $1
    exit 0
    ;;
esac
